version: "3.8"

services:
    app:
        image: pandawa-app:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - vendor_data:/var/www/html/vendor
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: mysql:lts
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    vendor_data:
